version: '3.5'

services:
  mssql:
    container_name: random_mssql
    image: 'mcr.microsoft.com/mssql/server'
    ports:
      - '1433:1433'
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Egemen.123
    volumes:
      - mssql_data:/var/opt/mssql
volumes:
  mssql_data:
    driver: local
